name: Upload Code Coverage
on: push

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.3'
      - name: Test
        run: swift test --enable-code-coverage
      - name: Generate
        run: ./.github/scripts/generate-code-coverage.sh
      - name: Upload
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./info.lcov
